# Generated by Django 4.2.24 on 2025-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('YourEmail', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deletiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('YourEmail', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
    ]
