# Generated by Django 4.2.24 on 2025-10-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contains_only_bullet_points', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('contains_bullet_points', models.BooleanField(default=False)),
                ('heading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='policy.heading')),
            ],
        ),
        migrations.AddField(
            model_name='heading',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='policy.policy'),
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('point', models.TextField()),
                ('heading_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='policy.headingdescription')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
