# Generated by Django 4.2.24 on 2025-11-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('validity', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BulletPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet', to='pricesection.pricesection')),
            ],
        ),
    ]
